apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.test.com
spec:
  group: stable.test.com
  versions:
  - name: v1
    served: true
    storage: true
    schema: 
      openAPIV3Schema:
        type: object
        properties:
          spec: 
            type: object
            properties:
              cronSpec:
                type: string
                pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                default: "5 0 * * *"
              image:
                type: string
              replicas:
                type: integer
                minimum: 1
                maximum: 10
          status:
            type: object
            properties:
              replicas:
                type: integer
              labelSelector:
                type: stringb
    subresources:
      status: {} 
      scale: 
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
        labelSelectorPath: .status.labelSelector
    additionalPrinterColumns:
    - name: Spec
      type: string
      description: Defines the interval
      jsonPath: .spec.cronSpec
    - name: Replicas
      type: integer
      description: Number of jobs
      jsonPath: .spec.replicas
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp  
  scope: Namespaced
  names: 
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
